[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudmetrics"
dynamic = ["version"]
requires-python = ">=3.10"
description = "Cloud pattern metrics toolkit"
readme = "README.md"
authors = [
    {name = "Leif Denby", email = "lcd@dmi.dk"},
    {name = "Martin Janssens", email = "martin.janssens@wur.nl"},
    {name = "Hauke Schulz", email = "has@dmi.dk"}
]
dependencies = [
    "scipy>=1.4.1",
    "PyWavelets>=1.1.1",
    "hilbertcurve>=2.0.5",
    "scikit-image>=0.16.2",
    "scikit-learn>=0.22.1",
    "matplotlib>=3.1.3",
    "seaborn>=0.10.0",
    "numba>=0.55.2"
]

[project.urls]
Homepage = "https://github.com/cloudsci/cloudmetrics"

[project.optional-dependencies]
test = [
    "pytest",
    "nbval"
]
dev = [
    "pytest",
    "nbval",
    "pre-commit",
    "ipython"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools_scm]
write_to = "cloudmetrics/_version.py"

[tool.isort]
profile = "black"
