name: linting

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  linting:
    name: "pre-commit hooks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - uses: pre-commit/action@v3.0.1
